FootTour/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("tournament.urls")),
    path("",include("adminapp.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from adminapp import views 
app_name='adminapp'
urlpatterns=[
    path('adminindex',views.adminindex,name='adminindex'),
    path('login',views.login,name='login'),
]

tournament/urls.py
from django.urls import path
from tournament import views 

app_name='tournament'
urlpatterns=[
    path('',views.index,name='index'),
    path('teamregistration',views.teamregistration,name='teamregistration'),
    path('teamdetails/<int:id>',views.teamdetails,name='teamdetails'),
    path('generate_schedule/', views.generate_first_round_schedule, name='generate_schedule'),
    path('fixturesandgoals',views.fixturesandgoals,name='fixturesandgoals'),
]

adminapp/models.py
from django.db import models

# Create your models here.
class TeamRegistration(models.Model):
    TeamName=models.CharField(max_length=500)
    Coach=models.CharField(max_length=500)
    Contact=models.CharField(max_length=500)
    Manager=models.CharField(max_length=500)
    Goalkeeper=models.CharField(max_length=500)
    Centreback=models.CharField(max_length=500)
    Sweeper=models.CharField(max_length=500)
    Wingback=models.CharField(max_length=500)
    Fullback=models.CharField(max_length=500)
    Central=models.CharField(max_length=500)
    Attacking=models.CharField(max_length=500)
    Wide=models.CharField(max_length=500)
    Secondstriker=models.CharField(max_length=500)
    Centreforward=models.CharField(max_length=500)
    Winger=models.CharField(max_length=500)
    Substitute1=models.CharField(max_length=500)
    Substitute2=models.CharField(max_length=500)
    Substitute3=models.CharField(max_length=500)
    Substitute4=models.CharField(max_length=500)

class Venue(models.Model):
    VenueName=models.CharField(max_length=500)
    Location=models.CharField(max_length=500,default='')

class Dates(models.Model):
    Startdate = models.DateField(default=None)
    Enddate = models.DateField(default=None)

class Times(models.Model):
    Firstmatch = models.TimeField()
    Secondmatch = models.TimeField()

class Schedule(models.Model):
    Team1 = models.ForeignKey('TeamRegistration', related_name='team1_matches', on_delete=models.CASCADE,default=None)
    Team2 = models.ForeignKey('TeamRegistration', related_name='team2_matches', on_delete=models.CASCADE,default=None)
    Match_date = models.DateField(default=None)
    Match_time = models.TimeField(default=None)
    Venue = models.ForeignKey('Venue', on_delete=models.CASCADE,default=None) 


class Result(models.Model):
    Schedule=models.ForeignKey('Schedule',on_delete=models.CASCADE)
    TeamName1=models.CharField(max_length=500)
    TeamName2=models.CharField(max_length=500)
    TeamScore1=models.CharField(max_length=500)
    TeamScore2=models.CharField(max_length=500)
    Match_date = models.DateField(null=True, blank=True,default=None)
    Match_time = models.TimeField(null=True, blank=True,default=None)

adminapp/views.py
from django.shortcuts import render
from adminapp.models import Venue,Dates,Times,Schedule,Result
from django.urls import reverse
from django.http import HttpResponse
from datetime import datetime
# Create your views here.

def login(request):
    if request.method=='POST':
        username=request.POST.get('name')
        password=request.POST.get('password')
        if username=='admin' and password=='1234':
            url = reverse('adminapp:adminindex')
            return HttpResponse(f'<script>alert("success"); window.location.href="{url}";</script>')
        else:
            url = reverse('adminapp:login')
            return HttpResponse(f'<script>alert("Incorrect data"); window.location.href="{url}";</script>')
    return render(request, 'adminapp/login.html')       
def adminindex(request):
    schedule=Schedule.objects.all()
    if request.method == 'POST':
        if 'venuename' in request.POST:
            Venue.objects.create(
                VenueName=request.POST.get('venuename'),
                Location=request.POST.get('location')
            )
            url = reverse('adminapp:adminindex')
            return HttpResponse(f'<script>alert("Venue added"); window.location.href="{url}";</script>')
        elif 'startdate' in request.POST:
            Dates.objects.create(
                Startdate=request.POST.get('startdate'),
                Enddate=request.POST.get('enddate')
            )
            url = reverse('adminapp:adminindex')
            return HttpResponse(f'<script>alert("Dates added"); window.location.href="{url}";</script>')
        elif 'firstmatch' in request.POST:
            Times.objects.create(
                Firstmatch=request.POST.get('firstmatch'),
                Secondmatch=request.POST.get('secondmatch')
            )
            url = reverse('adminapp:adminindex')
            return HttpResponse(f'<script>alert("Time added"); window.location.href="{url}";</script>')
        elif 'team1name' in request.POST:
            match_date_str = request.POST.get('matchdate')
            match_time = request.POST.get('matchtime')
            match_date = datetime.strptime(match_date_str, '%b. %d, %Y')
            
            schedule = Schedule.objects.get(Match_date=match_date, id=match_time)
            Result.objects.create(
                Schedule=schedule,
                TeamName1=request.POST.get('team1name'),
                TeamName2=request.POST.get('team2name'),
                TeamScore1=request.POST.get('team1score'),
                TeamScore2=request.POST.get('team2score'),
                Match_date=schedule.Match_date,
                Match_time=schedule.Match_time,
            )
            url = reverse('adminapp:adminindex')
            return HttpResponse(f'<script>alert("Result added"); window.location.href="{url}";</script>')

    return render(request, 'adminapp/index.html',{'schedule':schedule})

adminapp/templates/adminapp/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FootTour</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
</head>

adminapp/templates/adminapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% include 'adminapp/head.html' %}

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tournament:index' %}"><h3>FootTour</h3></a>
            <div class="dropdown pb-4">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'assets/images/usericon.jpg' %}" alt="hugenerd" width="30" height="30" class="rounded-circle">
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>
        
    </nav>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                        <li class="nav-item">
                            <a href="#" class="nav-link align-middle px-0">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col py-3">
                <div class="container mt-3">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-bs-toggle="tab" href="#venue">Add Venue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="tab" href="#dates">Add Dates</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="tab" href="#times">Add Time</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-bs-toggle="tab" href="#result">Add Result</a>
                        </li>
                    </ul>
            
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div id="venue" class="container tab-pane active"><br>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Venue Name <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" placeholder="Enter Venue Name" name="venuename" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Location <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" placeholder="Enter Location" name="location" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-6">
                                        <input type="submit" value="Register">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="dates" class="container tab-pane fade"><br>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Start Date <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="date" class="form-control" placeholder="Enter Start Date" name="startdate" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">End Date <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="date" class="form-control" placeholder="Enter End Date" name="enddate" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-6">
                                        <input type="submit" value="Register">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="times" class="container tab-pane fade"><br>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">First Match <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="time" class="form-control" placeholder="Enter Time1" name="firstmatch" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Second Match <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="time" class="form-control" placeholder="Enter Time2" name="secondmatch" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-6">
                                        <input type="submit" value="Register">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="result" class="container tab-pane fade"><br>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Date <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <select name="matchdate">
                                            {% for x in schedule %}
                                            <option value="{{x.Match_date}}">{{x.Match_date}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Time <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <select name="matchtime">
                                            {% for x in schedule %}
                                            <option value="{{x.id}}">{{x.Match_time}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Team1 <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <select name="team1name">
                                            {% for x in schedule %}
                                            <option value="{{x.Team1.TeamName}}">{{x.Team1.TeamName}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Team2 <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <select name="team2name">
                                            {% for x in schedule %}
                                            <option value="{{x.Team2.TeamName}}">{{x.Team2.TeamName}}</option>
                                            {% endfor %}
                                        </select>                                    
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Team1 Score<span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" placeholder="Enter Team1 Score" name="team1score" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-2">
                                        <label for="">Team2 <span style="color: red;">*</span></label>
                                    </div>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" placeholder="Enter Team1 Score" name="team2score" required>
                                    </div>
                                </div>
                                <div class="row row1">
                                    <div class="col-sm-6">
                                        <input type="submit" value="Register">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    


</body>

</html>

adminapp/templates/adminapp/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% include 'adminapp/head.html' %}

<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-sm-4"></div>
            <div class="col-sm-4" style="border: 1px solid gray; margin-top: 200px;padding: 50px;">
                <div class="container mt-3">
                    <a class="navbar-brand" href="#"><h3>FootTour</h3></a>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="row row1">
                            <div class="col-sm-4">
                                <label for="">User Name <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" placeholder="Enter  Name" name="name" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-4">
                                <label for="">Password <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" placeholder="Enter pasword" name="password" required>
                            </div>
                        </div>
                        <div class="row row1" style="float: right;">
                            <div class="col-sm-12">
                                <input type="submit" value="Login">
                            </div>
                        </div>
                    </form>
            </div>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>


</body>

</html>