FootTour/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("tournament.urls")),
    path("",include("adminapp.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from adminapp import views 
app_name='adminapp'
urlpatterns=[
    path('adminindex',views.adminindex,name='adminindex'),
    path('login',views.login,name='login'),
]

tournament/urls.py
from django.urls import path
from tournament import views 

app_name='tournament'
urlpatterns=[
    path('',views.index,name='index'),
    path('teamregistration',views.teamregistration,name='teamregistration'),
    path('teamdetails/<int:id>',views.teamdetails,name='teamdetails'),
    path('generate_schedule/', views.generate_first_round_schedule, name='generate_schedule'),
    path('fixturesandgoals',views.fixturesandgoals,name='fixturesandgoals'),
]

tournament/models.py
from django.db import models

# Create your models here.

tournament/views.py
from django.shortcuts import render,redirect
from adminapp.models import TeamRegistration,Schedule,Venue,Dates,Times,Result
from django.urls import reverse
from django.http import HttpResponse
from datetime import timedelta, date
from django.utils import timezone
# Create your views here.
def index(request):
    team=TeamRegistration.objects.all()
    return render(request,'tournament/index.html',{'team':team})
# Register a team
def teamregistration(request):
    schedule = Schedule.objects.all()  # Query existing schedule data
    team = TeamRegistration.objects.all()
    total_entries = TeamRegistration.objects.count()
    msg = "Sorry Registration Closed...." if total_entries >= 10 else ""

    if total_entries >= 10 and not Schedule.objects.exists():
        # Call the generate_first_round_schedule function
        generate_first_round_schedule(request)
        schedule = Schedule.objects.all()  
    if request.method=='POST':
        TeamRegistration.objects.create(
            TeamName=request.POST.get('teamname'),
            Coach=request.POST.get('coach'),
            Contact=request.POST.get('contact'),
            Manager=request.POST.get('manager'),
            Goalkeeper=request.POST.get('goalkeeper'),
            Centreback=request.POST.get('centreback'),
            Sweeper=request.POST.get('sweeper'),
            Wingback=request.POST.get('wingback'),
            Fullback=request.POST.get('fullback'),
            Central=request.POST.get('centralmidfielder'),
            Attacking=request.POST.get('attackingmidfielder'),
            Wide=request.POST.get('widemidfielder'),
            Secondstriker=request.POST.get('secondstriker'),
            Centreforward=request.POST.get('centreforward'),
            Winger=request.POST.get('winger'),
            Substitute1=request.POST.get('substitute1'),
            Substitute2=request.POST.get('substitute2'),
            Substitute3=request.POST.get('substitute3'),
            Substitute4=request.POST.get('substitute4'),
                )
        total_entries = TeamRegistration.objects.count()

        
        url = reverse('tournament:index')
        return HttpResponse(f'<script>alert("Registration Success."); window.location.href="{url}";</script>')   
    return render(request,'tournament/teamregistration.html',{'msg':msg,'team':team,'schedule':schedule})

def teamdetails(request,id):
    team=TeamRegistration.objects.all()
    teamdata=TeamRegistration.objects.get(id=id)
    return render(request,'tournament/teamdetails.html',{'teamdata':teamdata,'team':team})


def generate_first_round_schedule(request):
    dates=Dates.objects.get(id=1)
    times=Times.objects.get(id=1)
    start_date = dates.Startdate
    end_date = dates.Enddate
    first_match_time = times.Firstmatch
    second_match_time = times.Secondmatch

    
    predefined_venues = Venue.objects.all()

    # Calculate the number of teams and the number of days for the schedule
    teams = TeamRegistration.objects.all()
    num_teams = len(teams)
    num_days = (end_date - start_date).days + 1

    # Calculate matches per day (1 to 2 matches daily)
    matches_per_day = min(max(num_teams // num_days, 1), 2)

    # Create the schedule
    current_date = start_date
    current_match_time = first_match_time
    matches_created = 0

    while current_date <= end_date:
        # Create matches for the current date
        for _ in range(matches_per_day):
            if matches_created >= num_teams - 1:
                break  # All matches created
            # Fetch the venue for this match from the predefined venues
            venue = predefined_venues[matches_created % len(predefined_venues)]
            # Create a match record in the Schedule model
            match = Schedule(
                Team1=teams[matches_created],
                Team2=teams[matches_created + 1],
                Match_date=current_date,
                Match_time=current_match_time,
                Venue=venue,
            )
            match.save()
            matches_created += 2  # Move to the next pair of teams
            current_match_time = (
                second_match_time if current_match_time == first_match_time else first_match_time
            )

        # Move to the next day
        current_date += timezone.timedelta(days=1)

    return redirect('/teamregistration')
def fixturesandgoals(request):
    result=Result.objects.all()
    return render(request,'tournament/fixturesandgoals.html',{'result':result})

tournament/templates/tournament/fixturesandgoals.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% include 'tournament/head.html' %}
<body>
    {% include 'tournament/navigation.html' %}
    <div class="container-fluid mt-3">
            <div style="overflow-x:auto;">
            <table class="center">
                <tr>
                    <th>Team1</th>
                    <th>Team2</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Team1 Score</th>
                    <th>Team2 Score</th>
                    <th>Venue</th>
                    <th>Location</th>
                </tr>
                {% for sch in result %}
                <tr>
                    <td>{{sch.TeamName1}}</td>
                    <td>{{sch.TeamName2}}</td>
                    <td>{{sch.Schedule.Match_date}}</td>
                    <td>{{sch.Schedule.Match_time}}</td>
                    <td>{{sch.TeamScore1}}</td>
                    <td>{{sch.TeamScore2}}</td>
                    <td>{{sch.Schedule.Venue.VenueName}}</td>
                    <td>{{sch.Schedule.Venue.Location}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        
      </div>
    
    
    
    
    </body>
</html>

tournament/templates/tournament/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FootTour</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
</head>

tournament/templates/tournament/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% include 'tournament/head.html' %}
<body>
    {% include 'tournament/navigation.html' %}
    <div class="bg-image" style="background-image: url('{% static 'assets/images/main-bg.jpg' %}')">
        <div class="text-container">
            <a class="img-txt" href="{% url 'tournament:teamregistration' %}"><h3>Register Now!!</h3></a>
        </div>
    </div>
    
    
    </body>
</html>

tournament/templates/tournament/navigation.html
{% load static %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tournament:index' %}"><h3>FootTour</h3></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'tournament:index' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Squad</a>
                    <ul class="dropdown-menu">
                        {% for x in team %}
                        <li><a class="dropdown-item" href="{% url 'tournament:teamdetails' x.id %}">{{x.TeamName}}</a></li>
                        {% endfor %}
                    </ul>
                </li> 
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'tournament:fixturesandgoals'%}" >Fixtures &amp; Goals</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Admin</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'adminapp:login' %}">Login</a></li>
                    </ul>
                </li> 
            </ul>
        </div>
    </div>
</nav>

tournament/templates/tournament/teamdetails.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% include 'tournament/head.html' %}
<body>
    {% include 'tournament/navigation.html' %}
    <div class="bg-image" style="background-image: url('{% static 'assets/images/lawn.jpg' %}')">
        <div class="text-container">
            <div class="row">
                <div class="col">
                    <p class="team-head">{{teamdata.TeamName}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <p class="team-data">{{teamdata.Manager}}(manager)</p>
                </div>
                <div class="col-sm-6">
                    <p class="team-data">{{teamdata.Coach}}(coach)</p>
                </div>
            </div>
            <div class="row">
                <div class="col"></div>
                <div class="col">
                    <hr>
                </div>
                <div class="col"></div>
            </div>
            <div class="row">
                <div class="col"></div>
                <div class="col">
                    
                <p class="team-data">{{teamdata.Goalkeeper}}(goalkeeper)</p>    
                </div>
                <div class="col"></div>
            </div>
            <div class="row">     
                <div class="col-sm-3">
                    <p class="team-head">Defender</p> 
                    <p class="team-data">{{teamdata.Centreback}}</p>               
                    <p class="team-data">{{teamdata.Sweeper}}</p>
                    <p class="team-data">{{teamdata.Wingback}}</p> 
                    <p class="team-data">{{teamdata.Fullback}}</p> 
                </div>
                <div class="col-sm-3">
                    <p class="team-head">Midfielder</p>
                    <p class="team-data">{{teamdata.Central}}</p>
                    <p class="team-data">{{teamdata.Attacking}}</p>
                    <p class="team-data">{{teamdata.Wide}}</p>
                </div>
                <div class="col-sm-3">
                    <p class="team-head">Forward</p>
                    <p class="team-data">{{teamdata.Secondstriker}}</p>
                    <p class="team-data">{{teamdata.Centreforward}}</p>
                    <p class="team-data">{{teamdata.Winger}}</p>
                </div>
                <div class="col-sm-3">
                    <p class="team-head">Substitutes</p>
                    <p class="team-data">{{teamdata.Substitute1}}</p>
                    <p class="team-data">{{teamdata.Substitute2}}</p>
                    <p class="team-data">{{teamdata.Substitute3}}</p>
                    <p class="team-data">{{teamdata.Substitute4}}</p>
                </div>
            </div>
        </div> 
            </div>
        </div>
    </div>
    
    
    </body>
</html>

tournament/templates/tournament/teamregistration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% include 'tournament/head.html' %}
<body>
    {% include 'tournament/navigation.html' %}
    <div class="container-fluid mt-3">
        {% if msg %}
            <h3>{{msg}}</h3>
            <div style="overflow-x:auto;">
            <table class="center">
                <tr>
                    <th>Team1</th>
                    <th>Team2</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Venue</th>
                    <th>Location</th>
                </tr>
                {% for sch in schedule %}
                <tr>
                    <td>{{sch.Team1.TeamName}}</td>
                    <td>{{sch.Team2.TeamName}}</td>
                    <td>{{sch.Match_date}}</td>
                    <td>{{sch.Match_time}}</td>
                    <td>{{sch.Venue.VenueName}}</td>
                    <td>{{sch.Venue.Location}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% else %}
        <div class="row">
            <div class="col-sm-3 p-3">
                <img src="{% static 'assets/images/position.png' %}" class="float-start" alt="Paris" width="100%" height="100%"> 
            </div>
            <div class="col-sm-9 p-3">
                <div class="form-control">
                    <h5>Register Now</h5>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Team Name <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Team Name" name="teamname" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Contact No <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Contact" name="contact" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Coach <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Coach" name="coach" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Manager <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Manager" name="manager" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Goal Keeper <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Goal Keeper" name="goalkeeper" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <p>Defender</p>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Centre-Back <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Centreback" name="centreback" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Sweeper <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Sweeper" name="sweeper" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Wing-Back <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Wingback" name="wingback" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Full-Back <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Fullback" name="fullback" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <p>Midfielder</p>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Central <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Central Midfielder" name="centralmidfielder" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Attacking <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Attacking Midfielder" name="attackingmidfielder" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Wide <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Wide Midfielder" name="widemidfielder" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <p>Forward</p>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Second Striker <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Second Striker" name="secondstriker" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Centre Forward <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Centre Forward" name="centreforward" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Winger <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Winger" name="winger" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <p>Substitutes</p>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Substitute 1 <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Substitute1" name="substitute1" required>
                            </div>
                            <div class="col-sm-2">
                                <label for="">Substitute 2 <span style="color: red;">*</span></label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Substitute2" name="substitute2" required>
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col-sm-2">
                                <label for="">Substitute 3</label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Substitute3" name="substitute3">
                            </div>
                            <div class="col-sm-2">
                                <label for="">Substitute 4</label>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" placeholder="Enter Substitute4" name="substitute4">
                            </div>
                        </div>
                        <div class="row row1">
                            <div class="col">
                                <input type="submit" value="Register">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
      </div>
    
    
    
    
    </body>
</html>